### ISSUE TITLE
Artifacts disappearing with better graves

### ISSUE THREAD

**Issue by florensie** [florensie/artifacts-fabric#11]
https://www.curseforge.com/minecraft/mc-mods/artifacts-fabric?comment=28

**Comment by florensie** [comment]
Can't replicate.

**Comment by Rocco155** [comment]
I had the same problem, in a selfmade modpack with artifacts, allure and bettergraves. With disabling the grave function of the mod allure this problem was fixed. Together with allures grave function, the items also popped up when clicking a grave, instead of directly teleporting into the inventory in the old order as intended by bettergraves. This is also fixed by disabling the grave in allures configs.

**Comment by florensie** [comment]
@Rocco155 That's definitely an issue with Trinkets, and not likely to be related to this issue.
