### ISSUE TITLE
I need more info for config...

### ISSUE THREAD

**Issue by Abalieno** [florensie/artifacts-fabric#75]
both "artifactRarity" and "campsiteRarity" are too vague...

The first is set to 1.0, the second to 5.

Higher values would make those more rare across the world, or more frequent? How is that number scaling (like reducing their spawn chance to 50% of the default)?

**Comment by florensie** [comment]
**artifactsRarity:** higher is rarer, meaning less frequent. 2 is twice as rare as default, 0.5 is half as rare as default
**campsiteRarity:** on average, try to spawn a campsite every x (default 5) chunks. So higher is rarer here as well.

Also in the future, please use different channels for general question (Curseforge comments or discord). The issue tracker is only for feature requests and bugs/issues.

**Comment by Abalieno** [comment]
Well, it was a feature request in the sense that adding this to information within the cfg would be useful and avoid other people asking.

The chunk distance I guess isn't a radius, because as you can see from the screen below I have one camp spawned just a few blocks from another. They happen to be in two different chunks with an empty one in between.

Also, how does it choose where to spawn on the Y axis since there can be multiple caves and layers? I guess an algorithm that takes into consideration the raw distance from every camp isn't technically feasible.

Anyway, I'll try to experiment with those numbers.

![ytjuty](https://user-images.githubusercontent.com/4656436/188008227-245c0f4a-2272-4b86-9903-37a0ada4f0ac.jpg)

**Comment by florensie** [comment]
There is no "chunk distance", for every chunk generated it will check if it should spawn a campsite, which it will try 1 in 5 times (on average). This does not mean 1/5 of chunks have a campsite, as actually spawning a campsite can fail due due to space requirements etc.

The height placement is just wherever it finds sufficient room in the chunk, between y 96-32.

The configs are explained a little better when you edit them in-game (through mod menu). Adding these hints to the actual config files is planned with #44.

**Comment by Abalieno** [comment]
I didn't notice the in-game config, that's much better.

The slider for the camps is bad, though. It's impossible to set it correctly since it jumps way ahead. No granularity.
