### ISSUE TITLE
Add a name for the campsite structure in the registry.

### ISSUE THREAD

**Issue by glorification12** [florensie/artifacts-fabric#92]
**Is your feature request related to a problem? Please describe.**
I would like to be able to locate the underground campsites using the explorer's compass, but the structure doesn't seem to exist in the registry.

**Describe the solution you'd like**
An entry was added for the campsite structure allowing us to locate it.

**Describe alternatives you've considered**
Not many alternatives exist.

**Additional context**

**Comment by florensie** [comment]
This is not possible, because underground campsites are something called features, not structures. Features are usually more simple and also include stuff like trees and ore veins. Also, in my opinion it would be very OP to be able to find campsites that easily. If you think artifacts are too hard to find, you can tweak the config to make them less rare.
